"use strict";
const $ = id => document.getElementById(id);
const fmt = value => value == null ? "未知" : new Intl.NumberFormat("zh-TW").format(value);
const when = value => value ? new Date(value).toLocaleString("zh-TW", {hour12:false}) : "尚無紀錄";
const statusText = {ok:"完成",fallback:"Fallback",skipped:"略過 API",dry_run:"Dry run",running:"執行中",completed:"已完成",observed:"已觀察"};
function node(tag,text,cls){const element=document.createElement(tag);if(text!=null)element.textContent=text;if(cls)element.className=cls;return element;}
function cards(id,items){$(id).replaceChildren(...items.map(([label,value,detail])=>{const card=node("div",null,"card");card.append(node("div",label,"label"),node("div",value,"value"),node("div",detail,"detail"));return card;}));}
function cell(row,text,cls){row.append(node("td",text,cls));}
function chart(series){const svg=$("chart");svg.replaceChildren();const ns="http://www.w3.org/2000/svg";function add(tag,attrs,text){const el=document.createElementNS(ns,tag);for(const [key,value]of Object.entries(attrs))el.setAttribute(key,value);if(text)el.textContent=text;svg.append(el);}add("line",{x1:4,x2:636,y1:122,y2:122});if(!series.length){$("chart-note").textContent="目前沒有本機呼叫紀錄";return;}const max=Math.max(...series.map(s=>s.calls),1),width=620/series.length;series.forEach((s,i)=>{const h=s.calls/max*96;add("rect",{x:10+i*width,y:122-h,width:Math.max(1,width-3),height:h,rx:2});});add("text",{x:10,y:145},new Date(series[0].time).toLocaleString("zh-TW"));$("chart-note").textContent=`每小時操作次數, 最高 ${fmt(max)} 次; 顯示 ${series.length} 個有紀錄的時段`;}
function render(data){const j=data.jev,c=data.codex,s=j.summary||{};$("live").textContent="本機連線正常";$("jev-scope").textContent=`持續紀錄 ${j.enabled?"已啟用":"未啟用"} · 開始時間 ${when(j.enabled_at)} · ${j.health==="unavailable"?"資料暫時無法讀取":"只包含更新後 client 的已完成操作"}`;
cards("jev-cards",[["操作次數",fmt(s.calls||0),"Rank / Evaluate / Doctor"],["HTTP 嘗試",fmt(s.http_attempts||0),`其中 ${fmt(s.retries||0)} 次重試`],["Input tokens",fmt(s.input_tokens),`已知 ${fmt(s.input_known_calls||0)} 次, 未知 ${fmt(s.input_unknown_calls||0)} 次`],["Output tokens",fmt(s.output_tokens),`已知 ${fmt(s.output_known_calls||0)} 次, 未知 ${fmt(s.output_unknown_calls||0)} 次`]]);
$("statuses").replaceChildren(...["ok","fallback","skipped","dry_run"].map(status=>{const row=node("div",null,"status-row");row.append(node("span",statusText[status],`badge ${status}`),node("span",fmt((s.statuses||{})[status]||0)));return row;}));$("bytes").textContent=`平均操作耗時 ${fmt(s.average_latency_ms||0)} ms · Request body ${fmt(s.request_body_bytes||0)} bytes · 已知 response ${fmt(s.known_response_bytes||0)} bytes · 未知 response ${fmt(s.response_unknown_attempts||0)} 次; 非網路流量計費`;chart(j.series||[]);
$("jev-rows").replaceChildren(...(j.recent||[]).map(e=>{const row=node("tr");cell(row,when(e.timestamp));cell(row,`${e.operation} / ${e.source}`);cell(row,e.model||"未提供","mono");const td=node("td");td.append(node("span",statusText[e.status]||e.status,`badge ${e.status}`));row.append(td);cell(row,`${fmt(e.input_tokens)} / ${fmt(e.output_tokens)}`);cell(row,`${fmt(e.latency_ms)} ms`);cell(row,`${e.http_attempts} 次${e.attempts.length?" · "+e.attempts.map(a=>a.http_status||a.status).join(" → "):""}`);return row;}));$("jev-empty").textContent=j.recent?.length?"":j.enabled?"等待新的 Jev 操作; 既有 MCP process 需要重新載入才能使用新 client":"紀錄預設關閉; 啟用方式請參考 repo README";
$("codex-scope").textContent=c.health==="disabled"?"未啟用 Codex 紀錄讀取; 啟動時加上 --codex 可開啟":`觀察開始 ${when(c.started_at)} · 近期 ${fmt(c.files||0)} 個檔案的尾端與新增紀錄 · ${c.health}`;
cards("codex-cards",[["近期 Threads",fmt(c.threads?.length||0),"依 thread ID 合併重複來源"],["觀察到的工具呼叫",fmt(c.observed_tool_calls||0),"僅直接工具, 非完整歷史"],["工具種類",fmt(Object.keys(c.tools||{}).length),"不解析 exec 內容"],["本次讀取量",`${fmt(Math.round((c.bytes_read||0)/1024))} KiB`,"首次尾端 + 增量讀取"]]);
$("codex-rows").replaceChildren(...(c.threads||[]).map(t=>{const row=node("tr");cell(row,t.thread_id,"mono");cell(row,`${t.model||"未知"} / ${statusText[t.status]||t.status}`);for(const key of ["input_tokens","cached_input_tokens","output_tokens","reasoning_output_tokens","total_tokens"])cell(row,fmt(t.tokens[key]));cell(row,fmt(t.tool_calls));return row;}));$("codex-empty").textContent=c.threads?.length?"":"目前沒有可顯示的 Codex metadata";
$("tools").replaceChildren(...Object.entries(c.tools||{}).sort((a,b)=>b[1]-a[1]).map(([tool,count])=>{const el=node("span",tool,"tool");el.append(node("b",fmt(count)));return el;}));$("updated").textContent=`更新時間 ${when(data.updated_at)}`;}
let busy=false;
async function refresh(){if(busy)return;busy=true;try{const response=await fetch(`/api/snapshot?window=${encodeURIComponent($("window").value)}`,{cache:"no-store"});if(!response.ok)throw new Error("unavailable");render(await response.json());}catch{$("live").textContent="暫時無法連線, 將自動重試";}finally{busy=false;}}
$("window").addEventListener("change",refresh);refresh();setInterval(refresh,4000);
